name: Build and Deploy Code
on:
  push:
    branches:
      - "main"

jobs:
  build:
    env:
      DATABASE_HOSTNAME: ${{secrets.DATABASE_HOSTNAME}}
      DATABASE_NAME: ${{secrets.DATABASE_NAME}}
      DATABASE_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
      DATABASE_PORT: ${{secrets.DATABASE_PORT}}
      DATABASE_USERNAME: ${{secrets.DATABASE_USERNAME}}
      PAPER_DATABASE_NAME: ${{secrets.PAPER_DATABASE_NAME}}
      ABACUS_SECRET_KEY: ${{secrets.ABACUS_SECRET_KEY}}
      ABACUS_ALGORITHM: ${{secrets.ABACUS_ALGORITHM}}
      ABACUS_ACCESS_TOKEN_EXPIRE_MINUTES: ${{secrets.ABACUS_ACCESS_TOKEN_EXPIRE_MINUTES}}
      TD_CONSUMER_KEY: ${{secrets.TD_CONSUMER_KEY}}
      TD_ACCOUNT_NUMBER: ${{secrets.TD_ACCOUNT_NUMBER}}
      TD_REDIRECT_URI: ${{secrets.TD_REDIRECT_URI}}
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
          POSTGRES_DB: ${{secrets.DATABASE_NAME}}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    runs-on: ubuntu-latest
    steps:
      - name: Pulling git repo
        uses: actions/checkout@v2
      - name: Install python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: update pip
        run: python -m pip install --upgrade pip
      - name: install all dependencies
        run: pip install -r requirements.txt
      - name: test with pytest
        run: |
          pip install pytest
          pytest -s -v tests/deploy_tests

  deploy:
    runs-on: ubuntu-latest
    needs:
      - build

    steps:
      - name: Deploying to ubuntu server
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.UBUNTU_HOST}}
          username: ${{secrets.UBUNTU_USER}}
          password: ${{secrets.UBUNTU_PASSWORD}}
          scripts: |
            cd dev/abacus
            git pull
            echo ${{secrets.UBUNTU_PASSWORD}} | sudo -S systemctl restart Abacus
